from typing import List, Dict, Any
from schemas import AppSearchResponse, SearchResultItem, QuranMetadata, HadithMetadata
from gemini_llm import SearchModelOne, SearchModelTwo

def run_query(user_question: str, engine_quran, engine_hadith, model: SearchModelOne) -> AppSearchResponse:
    queries = model.generate_queries(user_question)
    

    query_results_map = []
    for q in queries:
        if q['type'] == "quran":
            engine = engine_quran
        else:
            engine = engine_hadith

        raw_results = engine.search(q['query'], top_k=5)
        query_results_map.append({
            'query': q['query'],
            'type': q['type'],
            'results': raw_results
        })
    
    
    validations_by_query = model.filter_results_batch(user_question, query_results_map)
    
    
    final_results = []
    seen_texts = set()
    
    for q_idx, item in enumerate(query_results_map):
        raw_results = item['results']
        validations = validations_by_query.get(q_idx, [])
        
        for val in validations:
            val_index = val['index']
            if val_index < 0 or val_index >= len(raw_results):
                continue
            if val['is_relevant']:
                res = raw_results[val_index]
                if res['text'] in seen_texts:
                    continue
                seen_texts.add(res['text'])
                meta_raw = res['metadata']
                if 'chapter' in meta_raw:
                    meta = QuranMetadata(chapter=meta_raw['chapter'], verse=meta_raw['verse'])
                else:
                    meta = HadithMetadata(
                        book=meta_raw.get('book', ''),
                        hadith_number=meta_raw.get('hadith_number', 0),
                        hadith_id=meta_raw.get('hadith_id')
                    )
                item = SearchResultItem(
                    text=res['text'],
                    metadata=meta,
                    score=res.get('score'),
                    is_relevant=True,
                    observation=val['observation']
                )
                final_results.append(item)

    return AppSearchResponse(
        user_question=user_question,
        generated_queries=queries,
        results=final_results
    )


def run_query_model_two(user_question: str, engine_quran, engine_hadith, model: SearchModelTwo) -> AppSearchResponse:
    queries = model.generate_queries(user_question)
    final_results = []
    seen_texts = set()

    for q in queries:
        if q['type'] == "quran":
            engine = engine_quran
        else:
            engine = engine_hadith

        raw_results = engine.search(q['query'],top_k=2)
        
        for res in raw_results:
            if res['text'] in seen_texts:
                continue
            seen_texts.add(res['text'])
            
            meta_raw = res['metadata']
            if 'chapter' in meta_raw:
                meta = QuranMetadata(chapter=meta_raw['chapter'], verse=meta_raw['verse'])
            else:
                meta = HadithMetadata(
                    book=meta_raw.get('book', ''),
                    hadith_number=meta_raw.get('hadith_number', 0),
                    hadith_id=meta_raw.get('hadith_id')
                )
            
            item = SearchResultItem(
                text=res['text'],
                metadata=meta,
                score=res.get('score'),
                is_relevant=True,
                observation="Generated by SearchModelTwo"
            )
            final_results.append(item)

    return AppSearchResponse(
        user_question=user_question,
        generated_queries=queries,
        results=final_results
    )